### ISSUE TITLE
RSS订阅出错

### ISSUE THREAD

**Issue by Auroraee** [jasongzy/MyUpdater#1]
学长，请问RSSHub的订阅链接报错怎么解决
route: njust/eo/_t1532/tzgg_14727/
Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>

**Comment by jasongzy** [comment]
我在本地部署的实例可以成功抓取这个订阅源：
![image](https://github.com/jasongzy/MyUpdater/assets/29547287/866ec64b-e655-4f12-8108-fa29eb4d3ba3)

爬级网依赖无头浏览器（Puppeteer），对服务器性能有比较大的影响，所以官方提供的公共实例跑起来可能存在各种问题，没有可用性保障，建议[自建](https://docs.rsshub.app/zh/deploy/)，或者在官方 Repo [发 issue](https://github.com/DIYgod/RSSHub/issues/new/choose) 等待他人帮助解决此问题。
